name: Compress Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    env:
      prepo: ${{github.repository}}
    steps:
      - uses: actions/checkout@v2
      - name: Creating branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'compressed-build'
          sha: '${{ github.event.pull_request.head.sha }}'
      - name: Removing unnecessary files
        run: |
          rm -r assets/scss
          ls -la
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i -g purgecss
      - run: ls -ls
      - run: ls -ls assets\css\bootstrap\
      - run: pwd
      - run: purgecss -h
      - run: purgecss --css assets\css\*.css --content index.html assets\js\**\*.js --output assets\css\
      - run: purgecss --css assets\css\bootstrap\*.css --content index.html assets\js\**\*.js --output assets\css\bootstrap\
      - run: purgecss --css assets\css\bootstrap\mixins\*.css --content index.html assets\js\**\*.js --output assets\css\bootstrap\mixins
      - run: purgecss --css assets\css\bootstrap\utilities\*.css --content index.html assets\js\**\*.js --output assets\css\bootstrap\utilities
      - run: purgecss --css assets\css\components\*.css --content index.html assets\js\**\*.js --output assets\css\components\
      - run: ls -ls assets\css\bootstrap\
      - name: minify css
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: 'assets/css'
      - name: minify js
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          directory: 'assets/js/custom'
      - name: Pushing to production branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: compressed-build
          message: Minified css, js and html
          author_name: MinifyAction[bot]
          author_email: amireshoon-minifyAction@users.noreply.github.com
          force: true